[mgr]
sort_by = "natural"
sort_dir_first = true
sort_translit = true
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
wrap = "yes"

[plugin]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
  { url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
  { mime = "application/sqlite3", run = 'piper -- sqlite3 "$1" ".schema --indent"' },
  { url = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]

[tasks]
image_alloc = 1073741824 # = 1024*1024*1024 = 1024MB
