live_config_reload = true
save_to_clipboard = true
"window.dynamic_title" = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#282c34"
blue = "#7cb7ff"
cyan = "#00c1e4"
green = "#71f79f"
magenta = "#c74ded"
red = "#ed254e"
white = "#dcdfe4"
yellow = "#f9dc5c"

[colors.normal]
black = "#282c34"
blue = "#7cb7ff"
cyan = "#00c1e4"
green = "#71f79f"
magenta = "#c74ded"
red = "#ed254e"
white = "#dcdfe4"
yellow = "#f9dc5c"

[colors.primary]
background = "#161925"
bright_foreground = "#828997"
dim_foreground = "#5c6370"
foreground = "#c3c7d1"

[cursor]
blinking = "On"
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 6

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/tmux"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 0.65
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 300
lines = 150
